# Generated by Django 6.1.1 on 2026-09-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
