# Generated by Django 6.1.1 on 2026-09-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trainees',
        ),
    ]
