# Generated by Django 6.1.1 on 2026-09-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainee', '0002_delete_trainees'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phono', models.IntegerField(unique=True)),
            ],
        ),
    ]
