# Generated by Django 6.1.1 on 2026-09-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainees',
            name='pfp',
            field=models.ImageField(blank=True, upload_to='trainee/images'),
        ),
    ]
